#!/bin/sh

mount proc /proc -t proc
mount sys /sys -t sysfs
mount -t tmpfs tmpfs /dev  -o size=64k,mode=0755
mkdir /dev/pts /dev/shm
mount -t devpts devpts /dev/pts
echo "/sbin/mdev" > /proc/sys/kernel/hotplug
mdev -s
